---
title: "Reproducible Research (RR) Course Goals"
author: "Keith Baggerly"
date: ''
output:
  pdf_document: default
  html_document: default
  word_document: default
---

# Things we want people to take away from the course

* an understanding of how RR can help in both the short and the long run
* an understanding of the importance of RR with big data, and what can happen when it breaks down
* an appreciation that the time for planning for reproducibility is ideally when the project starts, not when it ends, and some habits that can help with this
* knowledge of how to use literate programming with R/Rstudio/knitr/rmarkdown to produce reports with code and text interleaved to produce reports in html/pdf/word which others can read, run and check as desired
* knowledge of R packages for easier sharing, reuse, and potential publication
* knowledge of some issues currently hindering replication of many studies, and how some of these points can be addressed (batch effects, p-values, big data, sanity checks)
* knowledge of how to use git for version control
* knowledge of how to share git repositories with others
* an understanding of how to structure reports to improve clarity, utility, and likely progress
* knowledge of some places to go to learn more

# Background material (note live links!)

* [Baggerly and Coombes (2009)](https://projecteuclid.org/euclid.aoas/1267453942)
* [Broman Tools for RR Course](http://kbroman.org/Tools4RR/)
* [Gandrud 2e (2015)](http://www.amazon.com/Reproducible-Research-Studio-Second-Chapman-ebook/dp/B010ACWGBI/ref=tmm_kin_title_0?_encoding=UTF8&sr=&qid=)
* [NIH Rigor and Reproducibility Guidelines (2016)](https://www.nih.gov/research-training/rigor-reproducibility)
* [Peng Coursera course and notes (2013)](https://itunes.apple.com/us/book/id961495566?mt=11)
* [Retraction Watch](http://retractionwatch.com/)
* [Tabak and Collins (2014)](http://www.nature.com/news/policy-nih-plans-to-enhance-reproducibility-1.14586)
* [Wickham R Packages book (2015)](http://www.amazon.com/R-Packages-Hadley-Wickham-ebook/dp/B00VAYCHL0/ref=pd_sim_351_6?ie=UTF8&refRID=1E8HS30WBHRCW45SEWXM)
* [Xie 2e (2015)](http://www.amazon.com/Dynamic-Documents-knitr-Second-Chapman-ebook/dp/B00ZBYPJEW/ref=tmm_kin_title_0?_encoding=UTF8&sr=&qid=)

These references have different goals. 

Probably the best prep for the tools we hope folks will take away is Karl Broman's RR Tools course. More extensive discussions of many of these tools are given in the books by Gandrud, Peng, Xie and Wickham. Some discussions of sanity checks and breakdowns are given by Baggerly and Coombes. The NIH viewpoint and concerns are discussed by Tabak and Collins, and on the NIH Rigor and Reproducibility web page. Retraction Watch supplies more info on the sociological context.